## **01.넘파이**

### **1.1 넘파이 ndarray 개요**

**넘파이 array()함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행한다. 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있다.**

**ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환한다. ndarray.shape는 ndarray의 차원과 크기를 튜플(tuple)형태로 나타내준다.**

![test](./img/넘파이.png)

In [1]:
# numpy import 
import numpy as np

In [2]:
array1 = np.array([1,2,3]) # 1차원

In [3]:
print('array1 type:',type(array1)) # array1 변수 자료형 확인
print('array1 array 형태:',array1.shape) # array1의 형태 확인
print('array1:', array1) # array1 출력

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array1: [1 2 3]


- **[1,2,3]인 array1의 shape은 (3,)이다. 이는 1차원 array로 3개의 데이터를 가지고 있음을 뜻한다.**

In [4]:
array2 = np.array([[1,2,3],
                  [2,3,4]]) # 2차원

In [5]:
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)
print('array2: \n', array2)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array2: 
 [[1 2 3]
 [2 3 4]]


- **array2의 shape은 (2,3)으로 2차원의 2개의 로우와 3개의 컬럼으로 구성되어 2 * 3 = 6개의 데이터를 가지고 있음을 뜻한다.**

In [6]:
array3 = np.array([[1,2,3]]) # 2차원

In [7]:
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)
print('array3:',array3)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array3: [[1 2 3]]


- **[[1,2,3]] 역시 명확하게 로우와 칼럼으로 이뤄진 2차원 데이터임을 (1,3)으로 표현**

**머신러닝 알고리즘과 데이터세트 간의 입출력 변환을 수행하다 보면 명확히 1차원 데이터 또는 다차원 데이터를 요구하는 경우가 있다. 분명히 데이터값으로는 서로 동일하나 차원이 달라서 오류가 발생하는 경우가 빈번하다.**

In [8]:
print('array1 : {} , array2: {}, array3: {}'.format(array1.ndim,array2.ndim,array3.ndim))

array1 : 1 , array2: 2, array3: 2


- **리스트[]는 1차원이고, 리스트의 리스트 [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있다.**

In [9]:
list1 = [1,2,3] # 1차원
print(type(list1))
array1 = np.array(list1) # list1 (list) -> array형태로 변환
print(type(array1))
print(array1,array1.dtype) 

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


- **서로 다른 데이터 타입을 가질 수 있는 리스트와는 다르게 ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능하다고 했는데, 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용합니다.**

In [10]:
list2 = [1,2,'test'] # int형 유니코드 문자열 값으로 변환
array2 = np.array(list2)
print(array2,array2.dtype)

['1' '2' 'test'] <U11


In [11]:
list3 = [1,2,3.0] # float64로 변환
array3 = np.array(list3)
print(array3,array3.dtype)

[1. 2. 3.] float64


**ndarray 내 데이터 값의 타입 변경도 astype()메서드를 이용해 할 수 있다. astype()에 인자로 원하는 타입을 문자열로 지정하면 된다. 이렇게 데이터 타입을 변경하는 경우는 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 더 절약해야 할 때 보통 이용된다. 가령 int형으로 충분한 경우인데, 데이터 타입이 float라면 int형으로 바꿔서 메모리를 절약할 수 있다.**

In [12]:
array_int = np.array([1,2,3]) # int32
array_float = array_int.astype('float64') # int -> float64
print(array_float,array_float.dtype) 

[1. 2. 3.] float64


In [13]:
array_int1 = array_float.astype('int32') # float -> int32
print(array_int1,array_int1.dtype) 

[1 2 3] int32


In [14]:
array_float1 = np.array([1.1,2.1,3.1]) # float
array_int2 = array_float1.astype('int32') # float -> int
print(array_int2, array_int2.dtype)

[1 2 3] int32


### **ndarray를 편리하게 생성하기 - arange, zeros, ones**

**특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우가 발생할 수 있다. 이 경우 arange(),zeros(),ones()를 이용해 쉽게 ndarray를 생성할 수 있다.**

**주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용**

In [15]:
sequence_array = np.arange(10) # 0 ~ 9까지 연속된 숫자 할당
print(sequence_array)
print(sequence_array.dtype,sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [16]:
sequence_array1 = np.arange(0,20,2) # start, stop, by
print(sequence_array1)

[ 0  2  4  6  8 10 12 14 16 18]


**zero()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환한다. 유사하게 ones()는 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 1로 채운 해당 shape을 가진 ndarray를 반환한다.**

> - **함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채운다.**

In [17]:
zero_array = np.zeros((3,2),dtype='int32') # int32 3 * 2 zeros 배열 생성

In [18]:
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [19]:
ones_array = np.ones((3,3),dtype='float64')

In [20]:
ones_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### **ndarray의 차원과 크기를 변경하는 reshape()**

**reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환한다.**

In [21]:
array1 = np.arange(50)

In [22]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
array1.reshape(5,10) # 2차원

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [24]:
array1.reshape(2,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

**reshape()를 실전에서 더욱 효율적으로 사용하는 경우는 아마도 인자로 -1을 적용하는 경우일 것이다. -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해 줍니다.**

**array와 호환될 수 있는 n차원 ndarray로 변환하되 고정된 칼럼or로우에 호환될 수 있게 2차원 ndarray로 변환**

In [25]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
array2 = array1.reshape(-1,5) # 인자 -1을 적용하면 ndarray와 호환되는 새로운 shape으로 변환
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [27]:
array1 = np.arange(50) 
print(array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [28]:
array3 = array1.reshape(2,-1,5)
print(array3)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [29]:
# 다차원 배열을 무조건 1차원으로 펼치기 위해서는 faltten이나 ravel 함수를 사용한다.
array3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
array3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

**-1 인자는 reshape(-1,1)와 같은 혀태로 자주 사용된다. reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.**

**여러 개의 넘파이 ndarray는 stack이나 concat 결합할 때 각각의 ndarray의 형태를 통일해 유용하게 사용된다.**

In [31]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print(array3d.tolist()) # 리스트 자료형으로 변환할 수 있다.

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [32]:
array5 = array3d.reshape(-1,1) # 3차원 -> 2차원
print(array5,array5.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [33]:
array6 = array1.reshape(-1,1) # 1차원 -> 2차원
print(array6,array6.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


## **넘파이 ndarray의 데이터 세트 선택하기(인덱싱)**

**넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택할 수 있도록 하는 인덱싱에 대해 알아본다.**

> **1. 특정 데이터만 추출: 원하는 위치의 인덱스값을 지정하면 해당 위치의 데이터가 반환**

> **2. 슬라이싱(Slicing): 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식이다. ':'기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 위치에 있는 데이터의 ndarray를 반환한다. 예를들어 1:5라고 하면 시작 인덱스 1과 종료 인덱스 4까지에 해당하는 ndarray를 반환**

> **3. 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray형태로 지정해 해당 위치에 이쓴 데이터의 ndarray를 반환한다.**

> **4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 위치에 있는 데이터의 ndarray를 반환한다.**

In [ ]:
import numpy as np

In [ ]:
array1 = np.arange(1,10)
array1

In [ ]:
value = array1[2] # 2번째 인덱스 위치에 값을 할당
print('value:', value) 
print(type(value)) # array1[2]의 타입은 더 이상 ndarray 타입이 아니고 ndarray 내의 데이터값을 의미

In [ ]:
print('맨 뒤의 값:',array1[-1],'맨 뒤에서 두 번째 값:',array1[-2])

In [ ]:
# 단일 인덱스를 이용해 ndarray 내의 데이터 값도 간단히 수정 가능
array1[0] = 9
array1[8] = 0

In [ ]:
print('array1:',array1)

**다음으로 다차원 ndarray에서 단일 값을 추출. 3차원 이상의 ndarray에서의 데이터 추출도 2차원 ndarray와 큰 차이가 없으므로 더 간단한 이해를 위해 2차원 ndarray에서 단일 값을 추출**

**1차원과 2차원 ndarray에서의 데이터 접근의 차이는 2차원의 경우 콤마(,)로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근**

In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

In [ ]:
print(array2d[0,0]) # row = 0 , col = 0
print(array2d[0,1]) # row = 0 , col = 1
print(array2d[2,2]) # row = 2 , col = 2 
print(array2d[2,1]) # row = 2 , col = 1

![test](./img/축.png)

**위 그림에서 또 하나 주목해야 할 부분은 axis 0, axis 1이다. axis 0은 로우 방향의 축을 의미하고 axis 1은 칼럼 방향의 축을 의미한다.**

> **정확히 얘기하자면, 앞 설명에서 지칭한 로우와 칼럼은 넘파이 ndarray에서는 사용되지 않는 방식이다. 정확한 표현은 axis 0, axis 1 이다. 즉 [row=0,col=1] 인덱싱은 [aixs 0 = 0, axis 1 = 1]이 정확한 표현이다.**

> **다차원 ndarray의 경우 축(axis)에 따른 연산을 지원하기 때문에 방향 축을 이해하는 것이 중요하다.**

> **3차원 ndarray의 경우는 axis 0, axis 1, axis 2로 3개의 축을 가지게 된다.(행,열,높이로 이해)**

### **슬라이싱**

**':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있다. 단일 데이터값을 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입이다. ':'사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1이 위치에 있는 데이터의 ndarray를 반환**

In [ ]:
# 슬라이싱
array1 = np.arange(1,10) # 1 ~ 9까지 난수 생성
array3 = array1[0:3] # 0번째 인덱스에서 2번째 인덱스까지 데이터를 추출하여 array3에 할당
print(array3) # 출력
print(type(array3)) # 단일 데이터값 추출을 제외하고 나머지 인덱싱으로 추출된 데이터 세트는 ndarray

**슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생략이 가능**

> **1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맥 처음 인덱스인 0으로 간주**

> **2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주**

> **3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주**

In [ ]:
# 슬라이싱(생략)
array1 = np.arange(1,10)
array4 = array1[:3] # 0 ~ 2 번째 인덱스 까지
print(array4)

array5 = array1[3:] # 3 ~ 마지막 인덱스 까지
print(array5)

array6 = array1[:] # 전체 인덱스 
print(array6)

**이번에는 2차원 ndarray에서 슬라이싱으로 데이터에 접근**

> **2차원 ndarray에서의 슬라이싱도 1차원 ndarray에서의 슬라이싱과 유사하며, 단지 콤마(,)로 로우와 칼럼 인덱스를 지칭하는 부분만 다르다.**

In [ ]:
# 2차원 배열 슬라이싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

In [ ]:
print(array2d[:,0])
print(array2d[:,1])
print(array2d[1,:])
print(array2d[1,1:3])
print(array2d[2,:2])
print(array2d[1:3,1])

**2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환한다. 즉, array2d[0]과 같이 2차원에서 뒤에 오는 인덱스를 없애면 로우 축(axis 0)의 첫 번째 로우 ndarray를 반환하게 된다.**

In [ ]:
print(array2d[0]) # 2차원 -> 1차원
print(array2d[1]) # 2차원 -> 1차원
print('array2d[0] shape:',array2d[0].shape, 'array2d[1] shape:',array2d[1].shape)

### **팬시 인덱싱**

**팬시 인덱싱은 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치에 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방법이다. 2차원 ndarray에 팬시 인덱싱을 적용하면서 이 기능이 어떻게 동작하는지 살펴본다.**

![test](./img/팬시인덱싱.jpg)

In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

In [ ]:
array2d

In [ ]:
array3 = array2d[[0,1],2] # 인덱스가 (0,2) , (1,2)로 적용
array3.tolist()

In [ ]:
array4 = array2d[2,[1,2]] # 인덱스가 (2,1), (2,2)
array4.tolist()

In [ ]:
array5 = array2d[1:3,[0,1]] # ((1,0),(1,1)) , ((2,0),(2,1))
array5.tolist()

In [ ]:
array6 = array2d[1,[0,2]]
array6.tolist()

In [ ]:
array7 = array2d[[1,2]]
array7.tolist()

### **불린 인덱싱**

**불린 인덱싱은 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식이다.**

> **불린 인덱싱을 이용하면 for loop/if else 문보다 훨씬 간단하게 이를 구현할 수 있다.**

In [1]:
import numpy as np

In [2]:
array1d = np.arange(1,10)

In [3]:
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array3 = array1d > 5 # boolean indexing 적용

In [5]:
print('array1d > 5 불린 인덱싱 결과 값:',array3)

array1d > 5 불린 인덱싱 결과 값: [False False False False False  True  True  True  True]


**조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 []내에 입력하면 False값은 무시하고 True값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환하게 된다.**

> **위 예에서는 0 ~ 4는 무시하고 인덱스 [5,6,7,8]이 만들어지고 이 위치 인덱스에 해당하는 데이터 세트 [6,7,8,9]를 반환하게 된다.**

In [6]:
array_boolean = array1d[array3] # True 위치에 있는 인덱스 데이터 값 반환
print('불린 인덱스로 필터링 결과:',array_boolean)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [7]:
indexes = np.array([5,6,7,8]) # index 위치가 담긴 리스트
array4 = array1d[indexes] # 해당 위치 인덱스 데이터 값 반환
print(array4)

[6 7 8 9]


**불린 인덱싱이 동작하는 단계**

> **1. array1d > 5 와 같이 ndarray의 필터링 조건을 []안에 기재**

> **2. False 값은 무시하고 True값에 해당하는 인덱스 값(위치)을 저장**

> **3. 저장된 인덱스 데이터 세트로 ndarray 조회**

**불린 인덱싱은 내부적으로 여러 단계를 거쳐서 동작하지만, 코드 자체는 단순히 []내에 원하는 필터링 조건만 넣으면 해당 조건을 만족하는 ndarray 데이터 세트를 반홚기 때문에 사용자는 내부 로직에 크게 신경 쓰지 않고 쉽게 코딩할 수 있다.**

## **행렬의 정렬 - sort()와 argsort()**

### **행렬 정렬**

**넘파이 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있다.**

> **두 방식의 차이는 np.sort()의 경우 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환**

> **ndarray.sort()는 원 행렬 자체를 정렬한 형ㅇ태로 변환하며 반환 값은 None이다.**

In [8]:
org_array = np.array([3,1,9,5]) # 원본행렬

In [9]:
sort_array1 = np.sort(org_array)

In [10]:
# 원본 행렬과 새로 할당된 행렬 둘 다 존재
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1) # 변경 후
print('np.sort() 호출 후 반환된 원본 행렬:', org_array) # 변경 전 


np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 반환된 원본 행렬: [3 1 9 5]


In [24]:
# 기존의 원본 행렬만 변경
sort_array2 = org_array.sort()

In [25]:
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array() 호출 후 반환된 원본 행렬:', org_array) # 원본 행렬이 변경

org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array() 호출 후 반환된 원본 행렬: [1 3 5 9]


**원본 행렬에 대해서 np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환했으며, ndarray.sort()는 원본 행렬 자체를 정렬한 값으로 변환함을 알 수 있다.**

In [26]:
sort_array1_desc = np.sort(org_array)[::-1] # 내림 차순

In [27]:
sort_array1_desc

array([9, 5, 3, 1])

**행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있다.**

In [28]:
array2d = np.array([[8,12],
                   [7,1]])

In [29]:
sort_array2d_axis0 = np.sort(array2d,axis=0)
print('row 방향 정렬:\n',sort_array2d_axis0)

row 방향 정렬:
 [[ 7  1]
 [ 8 12]]


In [30]:
sort_array2d_axis1 = np.sort(array2d,axis=1)
print('column 방향 정렬:\n',sort_array2d_axis1)

column 방향 정렬:
 [[ 8 12]
 [ 1  7]]


### **정렬된 행렬의 인덱스를 반환하기**

**원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용한다.**

**np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환한다.**

In [31]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:',sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [32]:
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices_desc))
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [33]:
name = np.array(['승민','용민','형우','예신'])
score = np.array([80,50,65,70])

In [34]:
np.sort(score)

array([50, 65, 70, 80])

In [35]:
indexes = np.argsort(score)
print(indexes)

[1 2 3 0]


In [36]:
name[indexes]

array(['용민', '형우', '예신', '승민'], dtype='<U2')

**argsort()는 넘파이에서 매우 활용도가 높다.넘파이의 ndarray는 메타 데이터를 가질 수 없다. 따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarry로 각각 가져야만 한다. 예를 들어 학생별 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 시험 성적을 각각 ndarray로 가져야 한다. 이때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있으며, 이러한 방식은 넘파이의 데이터 추출에서 많이 사용된다.**

## **선형대수 연산 - 행렬 내적과 전치 행렬 구하기**

**넘파이는 매우 다양한 선형대수 연산을 지원한다. 그중 가장 많이 사용되면서도 기본 연산인 행렬 내적과 전치 행렬을 구하는 방법에 대해서 알아본다.**

### **행렬의 내적**

In [37]:
A = np.array([[1,2,3],
            [4,5,6]])
B = np.array([[1,3],
              [2,2,],
              [1,1]])

In [38]:
np.dot(A,B)

array([[ 8, 10],
       [20, 28]])

### **행렬의 전치**

In [39]:
A = np.array([[1,2],[3,4]])
print(A)

[[1 2]
 [3 4]]


In [40]:
transpose_mat = np.transpose(A)

In [41]:
print('행렬의 전치:\n',transpose_mat)

행렬의 전치:
 [[1 3]
 [2 4]]
